server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bono?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: bono
    password: 1234
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
            "[format_sql]": true